# Generated by Django 3.1 on 2021-02-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='유저 아이디')),
                ('user_grant', models.CharField(max_length=20, verbose_name='유저 권한')),
                ('user_name', models.CharField(blank=True, max_length=24, null=True, verbose_name='유저 이름')),
                ('user_age', models.DateTimeField(blank=True, null=True, verbose_name='유저 이름')),
                ('user_email', models.CharField(blank=True, max_length=20, null=True, verbose_name='유저 나이')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='유저 정보 업데이트일')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='유저 생성일')),
                ('del_yn', models.CharField(blank=True, max_length=24, null=True, verbose_name='삭제여부')),
            ],
            options={
                'verbose_name': '유저',
                'db_table': 'study_member',
                'managed': True,
            },
        ),
    ]
