# Generated by Django 3.1 on 2021-03-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "del_yn",
                    models.CharField(
                        blank=True,
                        choices=[("Y", "예"), ("N", "아니오")],
                        default="Y",
                        max_length=24,
                        null=True,
                        verbose_name="삭제여부",
                    ),
                ),
                ("update_date", models.DateTimeField(blank=True, null=True, verbose_name="업데이트일")),
                ("create_date", models.DateTimeField(blank=True, null=True, verbose_name="생성일")),
                ("user_index", models.AutoField(primary_key=True, serialize=True, verbose_name="유저 아이디")),
                (
                    "user_grant",
                    models.CharField(
                        choices=[("Admin", "관리자"), ("User", "사용자")],
                        default="Admin",
                        max_length=20,
                        verbose_name="유저 권한",
                    ),
                ),
                ("user_name", models.CharField(blank=True, max_length=24, null=True, verbose_name="유저 이름")),
                ("user_age", models.DateTimeField(blank=True, null=True, verbose_name="유저 이름")),
                ("user_email", models.CharField(blank=True, max_length=20, null=True, verbose_name="유저 나이")),
            ],
            options={
                "verbose_name": "유저",
                "db_table": "study_member",
                "managed": True,
            },
        ),
    ]
