# Generated by Django 3.1 on 2021-03-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnionMmeberWithComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('del_yn', models.CharField(blank=True, choices=[('Y', '예'), ('N', '아니오')], default='Y', max_length=24, null=True, verbose_name='삭제여부')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='업데이트일')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='생성일')),
                ('col1', models.CharField(blank=True, max_length=24, null=True, verbose_name='col1')),
                ('col2', models.CharField(blank=True, max_length=24, null=True, verbose_name='col2')),
            ],
            options={
                'verbose_name': '유저',
                'managed': False,
            },
        ),
    ]
