# Generated by Django 3.1 on 2021-03-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_unionmmeberwithcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='del_yn',
        ),
        migrations.RemoveField(
            model_name='member',
            name='update_date',
        ),
    ]
