# Generated by Django 3.1 on 2021-03-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='contents',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='내용'),
        ),
    ]
