# Generated by Django 3.1 on 2021-03-10 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_remove_cafe_comment_index'),
        ('comment', '0002_comment_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cafe_index',
            field=models.ForeignKey(db_column='cafe_index', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cafe_relate', to='cafe.cafe', verbose_name='cafe참조아이디'),
        ),
    ]
