# Generated by Django 3.1 on 2021-03-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('comment', '0003_comment_cafe_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_index',
            field=models.ForeignKey(db_column='user_index', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_relate2', to='member.member', verbose_name='member참조아이디'),
        ),
    ]
