# Generated by Django 3.1 on 2021-03-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_auto_20210313_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='del_yn',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='update_date',
        ),
    ]
