# Generated by Django 3.1 on 2021-02-27 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('board_index', models.AutoField(primary_key=True, serialize=False, verbose_name='게시판 아이디')),
                ('board_name', models.CharField(blank=True, max_length=24, null=True, verbose_name='게시판 이름')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='수정 이력')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='개설 날짜')),
                ('del_yn', models.CharField(blank=True, max_length=24, null=True, verbose_name='삭제여부')),
                ('user_index', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member.member', verbose_name='member참조아이디')),
            ],
            options={
                'verbose_name': '게시판',
                'db_table': 'study_board',
                'managed': True,
            },
        ),
    ]
