# Generated by Django 3.1 on 2021-02-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('cafe_index', models.AutoField(primary_key=True, serialize=False, verbose_name='카페 아이디')),
                ('cafe_name', models.CharField(blank=True, max_length=24, null=True, verbose_name='카페 이름')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='수정 이력')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='개설 날짜')),
                ('del_yn', models.CharField(blank=True, max_length=24, null=True, verbose_name='삭제여부')),
            ],
            options={
                'verbose_name': '카페',
                'db_table': 'study_cafe',
                'managed': True,
            },
        ),
    ]
