# Generated by Django 3.1 on 2021-03-02 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('del_yn', models.CharField(blank=True, choices=[('Y', '예'), ('N', '아니오')], default='Y', max_length=24, null=True, verbose_name='삭제여부')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='업데이트일')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='생성일')),
                ('cafe_index', models.AutoField(primary_key=True, serialize=False, verbose_name='카페 아이디')),
                ('cafe_name', models.CharField(blank=True, max_length=24, null=True, verbose_name='카페 이름')),
                ('user_index', models.ForeignKey(db_column='user_index', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cafe_order', to='member.member', verbose_name='member참조아이디')),
            ],
            options={
                'verbose_name': '카페',
                'db_table': 'study_cafe',
                'managed': True,
            },
        ),
    ]
