# Generated by Django 3.1 on 2021-03-10 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='user_index',
        ),
        migrations.AddField(
            model_name='cafe',
            name='comment_index',
            field=models.ForeignKey(db_column='comment_index', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_relate', to='comment.comment', verbose_name='commnet참조아이디'),
        ),
    ]
